#!/usr/bin/env python3
import argparse
import json
import os
import re
import sys
from pathlib import Path


EVIDENCE_WEIGHTS = {
    "crash-trace": 1.0,
    "poc-code": 0.8,
    "screenshot": 0.4,
    "description-only": 0.1,
    "ai-generated": 0.05,
}


TRACE_PATTERNS = {
    "asan": [
        r"==\d+==ERROR: AddressSanitizer:",
        r"SUMMARY:\s*AddressSanitizer:",
        r"heap-buffer-overflow",
        r"stack-buffer-overflow",
        r"global-buffer-overflow",
        r"heap-use-after-free",
        r"stack-use-after-return",
        r"double-free",
        r"malloc-size-sarific",
    ],
    "ubsan": [
        r"runtime error:",
        r"undefined behavior",
        r"signed integer overflow",
        r"shift exponent",
        r"null pointer",
    ],
    "valgrind": [
        r"==\d+==.*ERROR SUMMARY:",
        r"Invalid (read|write) of size",
        r"Conditional jump or move depends on uninitialised value",
        r"definitely lost: \d+ bytes",
    ],
    "gdb": [
        r"#\d+\s+0x[a-f0-9]+\s+in\s+\S+",
        r"Program received signal SIGSEGV",
        r"Program received signal SIGABRT",
        r"Core was generated by",
        r"BT:|Backtrace:",
    ],
}


POC_LANGUAGE_PATTERNS = {
    "c": [r"#include\s*<[a-z]+\.h>", r"int\s+main\s*\(", r"malloc\s*\(", r"free\s*\("],
    "cpp": [r"#include\s*<[a-z]+>", r"int\s+main\s*\(", r"new\s+\w+", r"delete\s+"],
    "python": [r"import\s+\w+", r"def\s+\w+\s*\(", r"ctypes\."],
    "rust": [r"fn\s+main\s*\(", r"unsafe\s*\{", r"use\s+\w+"],
    "go": [r"package\s+main", r"func\s+main\s*\("],
    "bash": [r"#!/bin/(ba|z)?sh", r"curl\s+", r"wget\s+"],
}


AI_PATTERNS = [
    r"As an AI",
    r"I'm an AI",
    r"generated by AI",
    r"as an AI language model",
    r"I cannot execute code",
    r"I do not have access to",
    r"Here's a hypothetical",
    r"Theoretically,",
    r"I've analyzed the code and found",
    r"Upon analysis,",
    r"Source: (ChatGPT|Claude|Copilot|Gemini)",
]


def detect_traces(body: str) -> dict:
    result = {"found": False, "types": [], "raw": []}
    for trace_type, patterns in TRACE_PATTERNS.items():
        for pattern in patterns:
            matches = re.findall(pattern, body, re.MULTILINE)
            if matches:
                result["found"] = True
                if trace_type not in result["types"]:
                    result["types"].append(trace_type)
                result["raw"].extend(matches[:5])
    return result


def detect_poc(body: str) -> dict:
    result = {"found": False, "languages": [], "code_blocks": []}
    code_blocks = re.findall(r"```(\w+)?\n(.*?)```", body, re.DOTALL)
    for lang, code in code_blocks:
        entry = {"language": lang or "unknown", "code_snippet": code[:200]}
        result["code_blocks"].append(entry)
        if not lang:
            for plang, patterns in POC_LANGUAGE_PATTERNS.items():
                if any(re.search(p, code) for p in patterns):
                    if plang not in result["languages"]:
                        result["languages"].append(plang)
                    result["found"] = True
        else:
            result["found"] = True
            if lang not in result["languages"]:
                result["languages"].append(lang)
    return result


def detect_screenshots(body: str) -> bool:
    return bool(re.search(r"!\[.*\]\(.*\.(png|jpg|jpeg|gif|svg)\)", body))


def detect_ai_generated(body: str) -> float:
    matches = sum(1 for p in AI_PATTERNS if re.search(p, body, re.IGNORECASE))
    if matches >= 3:
        return 0.95
    elif matches >= 1:
        return 0.7
    return 0.0


def score_report(body: str, report_data: dict = None) -> dict:
    traces = detect_traces(body)
    poc = detect_poc(body)
    screenshots = detect_screenshots(body)
    ai_conf = detect_ai_generated(body)

    evidence_types = []
    if traces["found"]:
        evidence_types.append("crash-trace")
    if poc["found"]:
        evidence_types.append("poc-code")
    if screenshots:
        evidence_types.append("screenshot")

    ai_flag = ai_conf > 0.5
    if ai_flag:
        evidence_types.append("ai-generated")

    if not evidence_types:
        evidence_types.append("description-only")

    score = max(EVIDENCE_WEIGHTS.get(t, 0) for t in evidence_types)
    if ai_flag and score > 0.05:
        score = min(score, 0.7)

    return {
        "score": round(score, 2),
        "evidence_types": evidence_types,
        "trace_details": traces,
        "poc_details": poc,
        "has_screenshots": screenshots,
        "ai_generated": ai_flag,
        "ai_confidence": round(ai_conf, 2),
    }


def format_verdict(scored: dict, min_score: float) -> dict:
    passed = scored["score"] >= min_score
    if not passed:
        msg_parts = []
        if scored["ai_generated"]:
            msg_parts.append("This report appears to be AI-generated.")
        if "crash-trace" not in scored["evidence_types"]:
            msg_parts.append("No sanitizer or crash trace provided.")
        if "poc-code" not in scored["evidence_types"]:
            msg_parts.append("No reproducible PoC code provided.")
        msg = " ".join(msg_parts) if msg_parts else "Insufficient evidence for triage."
    else:
        msg = "Evidence meets minimum threshold. Forwarding for triage."

    return {
        "verdict": "PASS" if passed else "INSUFFICIENT-EVIDENCE",
        "score": scored["score"],
        "threshold": min_score,
        "ai_generated": scored["ai_generated"],
        "message": msg,
    }


def main():
    parser = argparse.ArgumentParser("VulnGate — PoC-based vulnerability report gate")
    sub = parser.add_subparsers(dest="command")

    validate = sub.add_parser("validate")
    validate.add_argument("--report", help="JSON report file")
    validate.add_argument("--body", help="Raw report body text")
    validate.add_argument("--min-score", type=float, default=0.5)
    validate.add_argument("--output", help="Output file")

    extract = sub.add_parser("extract")
    extract.add_argument("--body", required=True, help="Raw text to extract traces from")
    extract.add_argument("--output", help="Output file")

    batch = sub.add_parser("batch")
    batch.add_argument("--input", required=True, help="Directory of report JSONs")
    batch.add_argument("--min-score", type=float, default=0.5)
    batch.add_argument("--output", default="scored-reports.json")

    args = parser.parse_args()

    if args.command == "validate":
        body = ""
        source_info = {}
        if args.body:
            body = args.body
        elif args.report:
            with open(args.report) as f:
                data = json.load(f)
            body = data.get("body", data.get("description", json.dumps(data)))
            source_info = data
        else:
            parser.error("Provide --body or --report")

        scored = score_report(body)
        verdict = format_verdict(scored, args.min_score)
        output = {**source_info, "evidence": scored, **verdict}

        out = json.dumps(output, indent=2)
        if args.output:
            with open(args.output, "w") as f:
                f.write(out)
        else:
            print(out)

    elif args.command == "extract":
        traces = detect_traces(args.body)
        poc = detect_poc(args.body)
        output = {"traces": traces, "poc": poc}
        out = json.dumps(output, indent=2)
        if args.output:
            with open(args.output, "w") as f:
                f.write(out)
        else:
            print(out)

    elif args.command == "batch":
        input_dir = Path(args.input)
        results = []
        for fpath in input_dir.glob("*.json"):
            with open(fpath) as f:
                data = json.load(f)
            body = data.get("body", data.get("description", json.dumps(data)))
            scored = score_report(body)
            verdict = format_verdict(scored, args.min_score)
            results.append({**data, "evidence": scored, **verdict})

        with open(args.output, "w") as f:
            json.dump({"reports": results, "total": len(results)}, f, indent=2)
        print(f"Scored {len(results)} reports → {args.output}")

    else:
        parser.print_help()


if __name__ == "__main__":
    main()
