#!/usr/bin/env python3
import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import List, Dict

SEVERITY_ORDER = {"none": 0, "note": 1, "warning": 2, "low": 2, "medium": 3, "high": 4, "error": 4, "critical": 5}


class Finding:
    def __init__(self, file_path: str, line: int, severity: str, rule: str, message: str):
        self.file_path = file_path
        self.line = line
        self.severity = severity
        self.rule = rule
        self.message = message

    def sev_score(self) -> int:
        return SEVERITY_ORDER.get(self.severity.lower(), 0)

    def __repr__(self):
        return f"[{self.severity.upper()}] {self.file_path}:{self.line} - {self.rule}: {self.message[:60]}"


class Remediation:
    def __init__(self, finding: Finding, patch: str, confidence: float, strategy: str):
        self.finding = finding
        self.patch = patch
        self.confidence = confidence
        self.strategy = strategy

    def __repr__(self):
        return f"Remediate({self.strategy}, conf={self.confidence:.2f}): {self.finding.rule}"


def parse_sarif(sarif_path: str) -> List[Finding]:
    findings = []
    with open(sarif_path) as f:
        data = json.load(f)
    for run in data.get("runs", []):
        for result in run.get("results", []):
            loc = result.get("locations", [{}])[0]
            phys = loc.get("physicalLocation", {})
            art = phys.get("artifactLocation", {})
            region = phys.get("region", {})
            finding = Finding(
                file_path=art.get("uri", "unknown"),
                line=region.get("startLine", 0),
                severity=result.get("level", "warning"),
                rule=result.get("ruleId", "unknown-rule"),
                message=result.get("message", {}).get("text", "No description"),
            )
            findings.append(finding)
    return findings


def parse_semgrep_json(json_path: str) -> List[Finding]:
    findings = []
    with open(json_path) as f:
        data = json.load(f)
    for result in data.get("results", []):
        findings.append(Finding(
            file_path=result.get("path", "unknown"),
            line=result.get("start", {}).get("line", 0),
            severity=result.get("extra", {}).get("severity", "warning"),
            rule=result.get("check_id", "unknown"),
            message=result.get("extra", {}).get("message", ""),
        ))
    return findings


def auto_triage(findings: List[Finding], threshold: str = "high") -> List[Finding]:
    min_sev = SEVERITY_ORDER.get(threshold.lower(), 3)
    return [f for f in findings if f.sev_score() >= min_sev]


def generate_remediation(finding: Finding) -> Remediation:
    strategies = {
        r"(?i)hardcoded.*(password|secret|key|token)": ("migrate-to-vault", 0.85),
        r"(?i)sql.*injection|sqli": ("parameterize-query", 0.90),
        r"(?i)xss|cross.?site.?script": ("add-output-encoding", 0.85),
        r"(?i)iam.*wildcard|\*.*action|\*.*resource": ("restrict-iam-action", 0.75),
        r"(?i)command.*injection|os.*command": ("sanitize-command", 0.80),
        r"(?i)path.*traversal": ("validate-path", 0.80),
        r"(?i)use.*after.*free|uaf": ("add-null-check", 0.70),
        r"(?i)buffer.*overflow": ("bounds-check", 0.70),
    }
    for pattern, (strategy, confidence) in strategies.items():
        if re.search(pattern, finding.message):
            patch = f"# TODO: {strategy} for {finding.rule} at {finding.file_path}:{finding.line}\n"
            patch += f"# Generated by PipelineShield auto-remediation\n"
            return Remediation(finding, patch, confidence, strategy)
    return Remediation(finding, "", 0.0, "unhandled")


def apply_remediation(remediation: Remediation, dry_run: bool = False) -> bool:
    if remediation.confidence < 0.6 or remediation.strategy == "unhandled":
        return False
    if dry_run:
        print(f"[DRY-RUN] Would apply {remediation}")
        return True
    file_path = remediation.finding.file_path
    line_no = remediation.finding.line
    patch = remediation.patch
    try:
        with open(file_path, "r") as f:
            lines = f.readlines()
        insert_line = min(line_no - 1, len(lines))
        lines.insert(insert_line, patch)
        with open(file_path, "w") as f:
            f.writelines(lines)
        print(f"  ✓ Applied {remediation.strategy} to {file_path}:{line_no}")
        return True
    except Exception as e:
        print(f"  ✗ Failed to apply remediation: {e}")
        return False


def create_pr_report(findings: List[Finding], remediations: List[Remediation]) -> str:
    report = ["# PipelineShield Remediation Report\n"]
    report.append(f"## Summary\n")
    report.append(f"- Total findings: {len(findings)}\n")
    auto_fixed = sum(1 for r in remediations if r.confidence > 0.6)
    unhandled = sum(1 for r in remediations if r.strategy == "unhandled")
    report.append(f"- Auto-remediated: {auto_fixed}\n")
    report.append(f"- Needs human review: {unhandled}\n")
    report.append(f"\n## Auto-Remediated\n")
    for r in remediations:
        if r.confidence > 0.6:
            report.append(f"- [{r.finding.severity.upper()}] {r.finding.file_path}:{r.finding.line}")
            report.append(f"  → {r.strategy} (confidence: {r.confidence:.0%})\n")
    report.append(f"\n## Needs Human Review\n")
    for r in remediations:
        if r.confidence <= 0.6 or r.strategy == "unhandled":
            report.append(f"- [{r.finding.severity.upper()}] {r.finding.file_path}:{r.finding.line}")
            report.append(f"  → {r.finding.message[:80]}\n")
    return "\n".join(report)


def main():
    parser = argparse.ArgumentParser(description="PipelineShield — Inline CI/CD remediation")
    parser.add_argument("--input-file", required=True, help="SARIF or Semgrep JSON input")
    parser.add_argument("--format", choices=["sarif", "semgrep", "auto"], default="auto")
    parser.add_argument("--severity-threshold", default="high")
    parser.add_argument("--auto-fix", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--output-report", help="Path for remediation report")
    args = parser.parse_args()

    if args.format == "auto":
        fmt = "semgrep" if "semgrep" in args.input_file else "sarif"
    else:
        fmt = args.format

    if fmt == "semgrep":
        findings = parse_semgrep_json(args.input_file)
    else:
        findings = parse_sarif(args.input_file)

    print(f"PipelineShield — parsed {len(findings)} total findings")

    triaged = auto_triage(findings, args.severity_threshold)
    print(f"Triage ({args.severity_threshold}+): {len(triaged)} findings")

    remediations = [generate_remediation(f) for f in triaged]
    auto_count = sum(1 for r in remediations if r.confidence > 0.6)
    unhandled_count = sum(1 for r in remediations if r.strategy == "unhandled")
    print(f"Auto-remediable: {auto_count} | Needs human: {unhandled_count}")

    if args.auto_fix:
        for r in remediations:
            apply_remediation(r, dry_run=args.dry_run)

    if args.output_report:
        report = create_pr_report(findings, remediations)
        with open(args.output_report, "w") as f:
            f.write(report)
        print(f"Report written to {args.output_report}")


if __name__ == "__main__":
    main()
